language: node_js
os: "linux"
dist: "focal"  
branches:
  only:
    - master
node_js:
  - "14.17.0"
cache:
  directories:
    - node_modules
before_install:
  - npm install npm@latest -g
  - npm --version
install:
  - npm install
before_script:
  - export TZ=Africa/Maseru
  - date
script:
  - npm run test-on-travis
after_script:
  - sed -i '$d' .gitignore
deploy:
  provider: azure_web_apps
  on:
    branch: master